name: functional_enum
description: Code generator for functional enum that makes the use of enums much better.
version: 1.1.3
homepage: https://github.com/Elias8/functional_enum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.0
  build: ^2.0.2
  build_config: ^1.0.0
  functional_enum_annotation: ^1.2.1
  source_gen: ^1.0.2
